#!/bin/sh
DIR=~/db

mkfifo $DIR/buffer$2.lm.db > /dev/null 2>&1 || true
mkfifo $DIR/buffer$2.db.lm > /dev/null 2>&1 || true

$DIR/lm/lm $1 $2 < $DIR/buffer$2.lm.db > $DIR/buffer$2.db.lm &
$DIR/db2/db $2 > $DIR/buffer$2.lm.db < $DIR/buffer$2.db.lm
